version: 0.2
phases:
  install:
    commands:
  #    - apt-get update -y
   # - apt install docker.io -y
  pre_build:
    commands:
      - $(aws ecr get-login)
      - TAG="latest"
  build:
    commands:
       - docker build --tag "${REPOSITORY_URI}:${TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${TAG}"        
