version: 0.2
phases:
  install:
    commands:
  #    - apt-get update -y
   # - apt install docker.io -y
  pre_build:
    commands:
     # - $(aws ecr get-login)
     # - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - mvn package
  post_build:
    commands:
      #- docker build --tag "${REPOSITORY_URI}:${TAG}" .
      #- docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s"}' $TAG > build.json
artifacts:
  files: 
        - build.json
        - target/gs-spring-boot-docker-0.1.0.jar
        
